#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Crystal version
#
# Usage: crenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Crystal
# version's `bin' directory is at the front.
#
# For example, if the currently selected Crystal version is 0.7.4:
#   crenv exec crystal deps
#
# is equivalent to:
#   PATH="$CRENV_ROOT/versions/0.7.4/bin:$PATH" crystal deps

set -e
[ -n "$CRENV_DEBUG" ] && set -x

# Provide crenv completions
if [ "$1" = "--complete" ]; then
  exec crenv shims --short
fi

CRENV_VERSION="$(crenv-version-name)"
CRENV_COMMAND="$1"

if [ -z "$CRENV_COMMAND" ]; then
  crenv-help --usage exec >&2
  exit 1
fi

export CRENV_VERSION
CRENV_COMMAND_PATH="$(crenv-which "$CRENV_COMMAND")"
CRENV_BIN_PATH="${CRENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`crenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$CRENV_VERSION" != "system" ]; then
  export PATH="${CRENV_BIN_PATH}:${PATH}"
  export CRYSTAL_PATH="${CRENV_ROOT}/versions/$(crenv-version-name)/src:libs:lib"
fi
exec -a "$CRENV_COMMAND" "$CRENV_COMMAND_PATH" "$@"
