#!/usr/bin/env bash
#
# Summary: Set or show the global Crystal version
#
# Usage: crenv global <version>
#
# Sets the global Crystal version. You can override the global version at
# any time by setting a directory-specific version with `crenv local'
# or by setting the `CRENV_VERSION' environment variable.
#
# <version> should be a string matching a Crystal version known to crenv.
# The special version string `system' will use your default system Crystal.
# Run `crenv versions' for a list of available Crystal versions.

set -e
[ -n "$CRENV_DEBUG" ] && set -x

# Provide crenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec crenv-versions --bare
fi

CRENV_VERSION="$1"
CRENV_VERSION_FILE="${CRENV_ROOT}/version"

if [ -n "$CRENV_VERSION" ]; then
  crenv-version-file-write "$CRENV_VERSION_FILE" "$CRENV_VERSION"
else
  crenv-version-file-read "$CRENV_VERSION_FILE" ||
  crenv-version-file-read "${CRENV_ROOT}/global" ||
  crenv-version-file-read "${CRENV_ROOT}/default" ||
  echo system
fi
