#!/usr/bin/env bash
# Summary: List all Crystal versions available to crenv
# Usage: crenv versions [--bare]
#
# Lists all Crystal versions found in `$CRENV_ROOT/versions/*'.

set -e
[ -n "$CRENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(crenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(crenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && CRENV_VERSION=system crenv-which crystal >/dev/null 2>&1; then
  print_version system
fi

for path in "${CRENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
