#!/usr/bin/env bash
# Summary: List existing crenv shims
# Usage: crenv shims [--short]

set -e
[ -n "$CRENV_DEBUG" ] && set -x

# Provide crenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${CRENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
