#!/usr/bin/env bash
# Summary: Detect the file that sets the current crenv version
set -e
[ -n "$CRENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.crystal-version" ]; then
      echo "${root}/.crystal-version"
      exit
    elif [ -e "${root}/.crenv-version" ]; then
      echo "${root}/.crenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$CRENV_DIR"
[ "$CRENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${CRENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${CRENV_ROOT}/global" ]; then
  echo "${CRENV_ROOT}/global"
elif [ -e "${CRENV_ROOT}/default" ]; then
  echo "${CRENV_ROOT}/default"
else
  echo "$global_version_file"
fi
