#!/usr/bin/env bash
set -e
[ -n "$CRENV_DEBUG" ] && set -x

# Provide crenv completions
if [ "$1" = "--complete" ]; then
  exec crenv-rehash --complete
fi

# When crenv shell integration is enabled, delegate to crenv-rehash,
# then tell the shell to empty its command lookup cache.
crenv-rehash
echo "hash -r 2>/dev/null || true"
