#!/usr/bin/env bash
# Summary: Explain how the current Crystal version is set
set -e
[ -n "$CRENV_DEBUG" ] && set -x

if [ -n "$CRENV_VERSION" ]; then
  echo "CRENV_VERSION environment variable"
else
  crenv-version-file
fi
