#!/usr/bin/env bash
# Summary: Detect the file that sets the current crenv version
set -e
[ -n "$CRENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -e "${root}/.crystal-version" ]; then
      echo "${root}/.crystal-version"
      return 0
    elif [ -e "${root}/.crenv-version" ]; then
      echo "${root}/.crenv-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

find_global_version_file() {
  local global_version_file="${CRENV_ROOT}/version"
  echo "$global_version_file"
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$CRENV_DIR" || {
    [ "$CRENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || find_global_version_file
fi
