#!/usr/bin/env bash
# Summary: Show the current Crystal version and its origin
#
# Shows the currently selected Crystal version and how it was
# selected. To obtain only the version string, use `crenv
# version-name'.

set -e
[ -n "$CRENV_DEBUG" ] && set -x

echo "$(crenv-version-name) (set by $(crenv-version-origin))"
