#!/usr/bin/env bash
# Summary: Show the current Crystal version
set -e
[ -n "$CRENV_DEBUG" ] && set -x

if [ -z "$CRENV_VERSION" ]; then
  CRENV_VERSION_FILE="$(crenv-version-file)"
  CRENV_VERSION="$(crenv-version-file-read "$CRENV_VERSION_FILE" || true)"
fi

if [ -z "$CRENV_VERSION" ] || [ "$CRENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${CRENV_ROOT}/versions/${version}" ]
}

if version_exists "$CRENV_VERSION"; then
  echo "$CRENV_VERSION"
elif version_exists "${CRENV_VERSION#crystal-}"; then
  { echo "warning: ignoring extraneous \`crystal-' prefix in version \`${CRENV_VERSION}'"
    echo "         (set by $(crenv-version-origin))"
  } >&2
  echo "${CRENV_VERSION#crystal-}"
else
  echo "crenv: version \`$CRENV_VERSION' is not installed" >&2
  exit 1
fi
