#!/usr/bin/env bash
# Summary: List all Crystal versions that contain the given executable
# Usage: crenv whence [--path] <command>

set -e
[ -n "$CRENV_DEBUG" ] && set -x

# Provide crenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec crenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  crenv-versions --bare | while read version; do
    path="$(crenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

CRENV_COMMAND="$1"
if [ -z "$CRENV_COMMAND" ]; then
  crenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$CRENV_COMMAND")"
[ -n "$result" ] && echo "$result"
